blog/urls.py
from blog.views import toggle_subscription
from django.urls import path, include
urlpatterns = [
    path(
        'api/',
        include([
            'toggle_subscription/<int:page_pk>/<category_pk>',
        ])
    )
]

blog_extension/urls.py
from django.urls.conf import path
from .views import submit_comment, toggle_subscription, contact_view
urlpatterns = [
    path('submit_form/', submit_comment, name='submit_comment'),
    path('toggle_subscription/',
         toggle_subscription, name='toggle_subscription'),
    path('contact_form/', contact_view, name='submit_contact_form')
]

app_name = 'blog_extension'

cmswagtail/urls.py
from blog.feeds import AtomFeed, RssFeed
from django.conf import settings
from django.conf.urls import url
from django.urls import include, path
from django.contrib import admin
from django.urls.conf import re_path
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls
from search import views as search_views
from django.views.generic import TemplateView
from wagtail.images.views.serve import ServeView
from wagtail.contrib.sitemaps.views import sitemap
urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('sitemap.xml', sitemap),
    path('robots.txt', include('robots.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),
    path('search/', search_views.search, name='search'),
    path('accounts/', include('allauth.urls')),
    path('accounts/login/success',
         TemplateView.as_view(template_name='account/redirect_login.html')),
    path('api/', include('blog_extension.urls')),
    path('rss/', RssFeed(), name='rssfeed'),
    path('atom/', AtomFeed(), name='atomfeed'),
]
if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
urlpatterns = urlpatterns + [
    re_path(r'^images/([^/]*)/(\d*)/([^/]*)/[^/]*$',
            ServeView.as_view(), name='wagtailimages_serve'),
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),
    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

search/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.template.response import TemplateResponse
from wagtail.core.models import Page
from wagtail.search.models import Query


def search(request):
    search_query = request.GET.get('query', None)
    page = request.GET.get('page', 1)
    # Search
    if search_query:
        search_results = Page.objects.live().search(search_query)
        query = Query.get(search_query)
        # Record hit
        query.add_hit()
    else:
        search_results = Page.objects.none()
    # Pagination
    # paginator = Paginator(search_results, 10)
    # try:
    #     search_results = paginator.page(page)
    # except PageNotAnInteger:
    #     search_results = paginator.page(1)
    # except EmptyPage:
    #     search_results = paginator.page(paginator.num_pages)
    return TemplateResponse(request, 'search/search.html', {
        'search_query': search_query,
        'search_results': search_results,
    })

cmswagtail/templates/base.html
{% load static wagtailuserbar %}
{% load wagtailcore_tags wagtailimages_tags %}
<!DOCTYPE html>
<html lang="en" dir="ltr"
   prefix="content: http://purl.org/rss/1.0/modules/content/  dc: http://purl.org/dc/terms/  foaf: http://xmlns.com/foaf/0.1/  og: http://ogp.me/ns#  rdfs: http://www.w3.org/2000/01/rdf-schema#  schema: http://schema.org/  sioc: http://rdfs.org/sioc/ns#  sioct: http://rdfs.org/sioc/types#  skos: http://www.w3.org/2004/02/skos/core#  xsd: http://www.w3.org/2001/XMLSchema# ">
<!-- Mirrored from comet2.drupalet.com/ by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 13 Apr 2021 05:34:01 GMT -->
<!-- Added by HTTrack -->
<meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->

<head>
   <title>getHarsh.in()</title>
   <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
   <meta charset="utf-8" />
   <meta name="MobileOptimized" content="width" />
   <meta name="HandheldFriendly" content="true" />
   <meta name="viewport" content="width=device-width, initial-scale=1.0" />
   {% block head-scripts %}
   {% endblock head-scripts %}

   {% block head-styles %}
   {% endblock head-styles %}

   <script src="https://kit.fontawesome.com/895abefc57.js" crossorigin="anonymous"></script>
   <script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>
   <link rel="shortcut icon" href="{% static 'images/fav/fav512x512.png' %}" type="image/vnd.microsoft.icon" />
   <link rel="stylesheet"
      href="{% static 'core/themes/stable/css/system/components/ajax-progress.module87a5.css' %}" media="all" />
   <link rel="stylesheet"
      href="{% static 'core/themes/stable/css/system/components/autocomplete-loading.module87a5.css' %}"
      media="all" />
   <link rel="stylesheet"
      href="{% static 'core/themes/stable/css/system/components/fieldgroup.module87a5.css' %}" media="all" />
   <link rel="stylesheet"
      href="{% static 'core/themes/stable/css/system/components/container-inline.module87a5.css' %}"
      media="all" />
   <link rel="stylesheet" href="{% static 'core/themes/stable/css/system/components/clearfix.module87a5.css' %}"
      media="all" />
   <link rel="stylesheet" href="{% static 'core/themes/stable/css/system/components/details.module87a5.css' %}"
      media="all" />
   <link rel="stylesheet" href="{% static 'core/themes/stable/css/system/components/hidden.module87a5.css' %}"
      media="all" />
   <link rel="stylesheet" href="{% static 'core/themes/stable/css/system/components/item-list.module87a5.css' %}"
      media="all" />
   <link rel="stylesheet" href="{% static 'core/themes/stable/css/system/components/js.module87a5.css' %}"
      media="all" />
   <link rel="stylesheet" href="{% static 'core/themes/stable/css/system/components/nowrap.module87a5.css' %}"
      media="all" />
   <link rel="stylesheet"
      href="{% static 'core/themes/stable/css/system/components/position-container.module87a5.css' %}"
      media="all" />
   <link rel="stylesheet" href="{% static 'core/themes/stable/css/system/components/progress.module87a5.css' %}"
      media="all" />
   <link rel="stylesheet"
      href="{% static 'core/themes/stable/css/system/components/reset-appearance.module87a5.css' %}"
      media="all" />
   <link rel="stylesheet" href="{% static 'core/themes/stable/css/system/components/resize.module87a5.css' %}"
      media="all" />
   <link rel="stylesheet"
      href="{% static 'core/themes/stable/css/system/components/sticky-header.module87a5.css' %}" media="all" />
   <link rel="stylesheet" href="{% static 'core/themes/stable/css/system/components/tabledrag.module87a5.css' %}"
      media="all" />
   <link rel="stylesheet" href="{% static 'core/themes/stable/css/system/components/tablesort.module87a5.css' %}"
      media="all" />
   <link rel="stylesheet"
      href="{% static 'core/themes/stable/css/system/components/tree-child.module87a5.css' %}" media="all" />
   <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700" media="all" />
   <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:300,400,500" media="all" />
   <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Halant:300,400" media="all" />
   <link rel="stylesheet" href="{% static 'themes/custom/getharsh/css/bundle87a5.css' %}" media="all" />
   <link rel="stylesheet" href="{% static 'themes/custom/getharsh/css/style87a5.css' %}" media="all" />
   <link rel="preconnect" href="https://fonts.gstatic.com">
   <link
      href="https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@200;400;600;900&family=Source+Serif+Pro&display=swap"
      rel="stylesheet">
   <link rel="preconnect" href="https://fonts.gstatic.com">
   <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville&display=swap" rel="stylesheet">
   <link rel="preconnect" href="https://fonts.gstatic.com">
   <link href="https://fonts.googleapis.com/css2?family=Heebo&display=swap" rel="stylesheet">
   <link rel="preconnect" href="https://fonts.gstatic.com">
   <link href="https://fonts.googleapis.com/css2?family=Heebo&family=Roboto+Slab&display=swap" rel="stylesheet">
   <!--[if lte IE 8]>
<script src="/core/assets/vendor/html5shiv/html5shiv.min.js?v=3.7.3"></script>
<![endif]-->
   <style type="text/css" media="all">
      #getharsh-message {
         display: none !important
      }
   </style>
   <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
   <script async src='cdn-cgi/bm/cv/669835187/api.js'></script>

</head>

<body>
   {% wagtailuserbar %}
   <div id="loader">
      <div class="centrize">
         <div class="v-center">
            <div id="mask">
               <span></span>
               <span></span>
               <span></span>
               <span></span>
               <span></span>
            </div>
         </div>
      </div>
   </div>
   <header id="topnav">
      <div style="background-color: #f3f2ec" class="logo">
         <a href="/">
            <img src="{% static 'images/LOGOW.png' %}" class="img-back" />
            <img src="{% static 'images/LOGOB.png' %}" class="img-top"/>
         </a>
         </div>
      <div class="container">
         <!-- <div id="block-getharsh-branding" class="logo">
            <a href="/">
               <img src="{% static 'images/blacklogo.png' %}" width="auto" height="auto"
                  alt="Comet - Creative Multi-Purpose Drupal 8 Theme" class="logo-light">
               <img src="{% static 'images/blacklogo.png' %}" width="auto" height="auto"
                  alt="Comet - Creative Multi-Purpose Drupal 8 Theme" class="logo-dark">
            </a>
         </div> -->
         <div class="menu-extras">
            <div class="menu-item">
               <div class="search">
                  <a href="{% url 'search' %}" onclick="goToSearch()">
                     <i class="fas fa-search"></i>
                  </a>
               </div>
            </div>
            <div class="menu-item">
               <a class="navbar-toggle">
                  <div class="lines">
                     <span></span>
                     <span></span>
                     <span></span>
                  </div>
               </a>
            </div>
         </div>
         <div id="navigation" style="background-color: b71c1c;">
            <h2 class="visually-hidden">Main navigation</h2>
            <ul class="navigation-menu">
               <li class="getharsh-megamenu">
                  <a></a>
               </li>
               {% for menuitem in menuitems %}
               <li class="getharsh-megamenu">
                  <a href="{% pageurl menuitem %}" style="font-weight: 900;">{{ menuitem.title }}</a>
               </li>
               {% endfor %}
               
               {% if user.is_authenticated %}
                  {% include 'components/authentication/logout.html' %}
               {% else %}
               <li class="getharsh-megamenu">
                  <a href="#" data-toggle="modal" title="Login" data-target="#loginModal" style="font-weight: 800;"><i class="fa fa-sign-in" aria-hidden="true"></i>Login</a>
               </li>
               {% endif %}

               <li class="getharsh-megamenu">
                  <a href="https://discord.com/widget?id=815798019315466282&theme=dark"
                     style="font-weight: 900;"><i class="fab fa-discord fa-2x"></i></a>
               </li>
            </ul>
         </div>
      </div>
   </header>
   {% include 'components/subscribe_modal.html' %}
   {% include 'components/authentication/login.html' %}

   {% block content %}
   {% endblock content %}
   <script data-cfasync="false"
      src="{% static 'cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js' %}"></script>
   <script type="application/json"
      data-drupal-selector="drupal-settings-json">{"path":{"baseUrl":"\/","scriptPath":null,"pathPrefix":"","currentPath":"node","currentPathIsAdmin":false,"isFront":true,"currentLanguage":"en"},"pluralDelimiter":"\u0003","ajaxTrustedUrl":{"\/search\/node":true},"user":{"uid":0,"permissionsHash":"43855dfde26144eea82393dafa3b75a2dabb8b7591eaefb677bdc4524fbdaa33"}}</script>
   <script src="{% static 'core/assets/vendor/domready/ready.min7016.js' %}"></script>
   <script src="{% static 'core/assets/vendor/jquery/jquery.min63b9.js' %}"></script>
   <script src="{% static 'themes/custom/getharsh/js/custom-getharshfe9e.js' %}"></script>
   <script src="{% static 'themes/custom/getharsh/js/bundlefe9e.js' %}"></script>
   <script src="{% static 'themes/custom/getharsh/js/mainfe9e.js' %}"></script>
   <script src="{% static 'themes/custom/getharsh/js/updatefe9e.js' %}"></script>
   <script src="{% static 'core/assets/vendor/jquery/jquery3.6.0.js' %}"></script>
   <script
      type="text/javascript">(function () { window['__CF$cv$params'] = { r: '63f252b0a90f069e', m: '5e6f06999e1978deaae419f61ce1b86043821ae9-1618292044-1800-ATlDH/LXBkV4etrn+aXe//K3RzSR4iRJuJGG0oZxStyQTh0/ukMnXNv+vbWVFQj/4bz34fpibkvTRH69QjGaUYb63icazjxHAqH1PBC1kd7BbjaoBnAyWD2boXw5y4hT9Q==', s: [0x3f48b7633b, 0xb77587025c], } })();</script>
   <script src="{% static 'extras/js/velocity.min.js' %}"></script>
   <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
   <!-- Subscribe Modal Script -->
   <script>
      $("#MyLink").click(function () {
         mixpanel.track("Clicked Link");
      })
   </script>
   <script>
      function goToSearch() {
         location = "{% url 'search' %}";
      }
   </script>
   <script type="text/javascript">
      function selectAllCategoriesInModal() {
         const ele = document.querySelectorAll('label.btn>input');
         ele.forEach((value) => {
            $(value).prop('checked', true)
            $(value.parentElement).addClass('active')
         })
      }
      function unSelectAllCategoriesInModal() {
         const ele = document.querySelectorAll('label.btn>input');
         ele.forEach((value) => {
            $(value).prop('checked', false);
            $(value.parentElement).removeClass('active')
         })
      }
   </script>
   <script>
      $('#submitSubscribeModal').click(
         function () {
            $('#subscribe-form').submit();
         }
      );
      $('#subscribe-form').on('submit',
         function (e) {
            e.preventDefault();
            const submit_button = $('#submitSubscribeModal');
            submit_button.prop('disabled', true);
            const revertSubmit = () => {
               submit_button.removeClass('btn-primary');
               submit_button.addClass('btn-color-out');
               submit_button.attr('value', 'Save your Subscriptions');
               submit_button.prop('disabled', false);
            };
            submit_button.addClass('btn-primary');
            submit_button.removeClass('btn-color-out')
            submit_button.attr('value', 'Save Changes');
            $.ajax({
               type: 'POST',
               url: "{% url 'blog_extension:toggle_subscription' %}",
               data: $(this).serialize(),
               success: function (response) {
                  revertSubmit();
                  let currentSubs = response.current_subscriptions;
                  console.log(currentSubs)
                  currentSubs = currentSubs != '' ? currentSubs : 'None'
                  swal('Your Changes have been saved',
                     `Current Subscription: ${currentSubs}`,
                     'success')
                     .then(() => {
                        $('#closeSubscribeModal').click();
                     });
               },
               error: function (response) {
                  revertSubmit();
                  swal('Your Changes could not be saved.', 'Please Reload the Page.', 'error')
                     .then(() => {
                        $('#closeSubscribeModal').click();
                     });
               }
            })
         }
      );
      $(document).ready(function () {
         document.querySelectorAll('.navigation-menu >li').forEach((value) => value.classList.remove('active'));
      })
   </script>
   <!-- Subscribe Modal Script -->
   {% block scripts %}
   {% endblock scripts %}
</body>

</html>

cmswagtail/templates/search.html
<style>
.search-page{
    position: absolute;
    width: 100%;
    height: 100%;
}
.search-page
</style>
<div class="search-page">
    
</div>

cmswagtail/templates/youtube_carousel.html
<!DOCTYPE html>
<head>
	<style>
	* {
		-webkit-box-sizing: border-box;
		-moz-box-sizing: border-box;
		-ms-box-sizing: border-box;
		-o-box-sizing: border-box;
		box-sizing: border-box;
		margin:0;
		padding:0;
	}
	html {
		font-size: 16px;
		background-color:#000;
	}
	body {
		font-family: Arial, sans-serif;
		color: #545454;
		max-width:600px;
		margin:10px auto;
	}
	/* Additionnal styles */
	.video-slider {
		width: 100%;
		height: 20em;
		background: #444;
		position: relative;
		overflow: hidden;
	}
	.slide {
		position: absolute;
		top: 0;
		left: 100%;
		height: 100%;
		width: 100%;
		text-align: center;
		overflow: hidden;
	}
	.slide:first-child{
		left: 0;
	}
	.video{
		height: 100%;
		width: 100%;
		border:0;
	}
	.slide-arrow{
		position: absolute;
		top: 0;
		left: 0;
		height: 45%;
		width: 15%;
		cursor: pointer;
		opacity: .2;
	}
	.slide-arrow:hover{
		opacity: 1;
	}
	.slide-arrow:after{
		content: "\003c";
		text-align: center;
		display: block;
		height: 10%;
		width: 100%;
		position: absolute;
		bottom: 0;
		left: 0;
		font-size: 3em;
	}
	.slide-arrow.right:after{
		content: "\003e";
	}
	.slide-arrow.right{
		left: auto;
		right: 0;
	}
	</style>
	<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
	<script src="https://www.youtube.com/iframe_api"></script>
	<script>
	$(document).ready(function () {
		var pos = 0,
			slides = $('.slide'),
			numOfSlides = slides.length;
		function nextSlide() {
			// `[]` returns a vanilla DOM object from a jQuery object/collection
			slides[pos].video.stopVideo()
			slides.eq(pos).animate({ left: '-100%' }, 500);
			pos = (pos >= numOfSlides - 1 ? 0 : ++pos);
			slides.eq(pos).css({ left: '100%' }).animate({ left: 0 }, 500);
		}
		function previousSlide() {
			slides[pos].video.stopVideo()
			slides.eq(pos).animate({ left: '100%' }, 500);
			pos = (pos == 0 ? numOfSlides - 1 : --pos);
			slides.eq(pos).css({ left: '-100%' }).animate({ left: 0 }, 500);
		}
		$('.left').click(previousSlide);
		$('.right').click(nextSlide);
	})
	function onYouTubeIframeAPIReady() {
		$('.slide').each(function (index, slide) {
			// Get the `.video` element inside each `.slide`
			var iframe = $(slide).find('.video')[0]
			// Create a new YT.Player from the iFrame, and store it on the `.slide` DOM object
			slide.video = new YT.Player(iframe)
		})
	}
	</script>
</head>
<body>
	<div class="video-slider">
		<!-- SLIDE 1 -->
		<div class="slide">
			<iframe class="video" src="https://www.youtube.com/embed/YE7VzlLtp-4?ecver=2&enablejsapi=1"></iframe>
		</div>
		<!-- SLIDE 2 -->
		<div class="slide">
			<iframe class="video" src="https://www.youtube.com/embed/YE7VzlLtp-4?ecver=2&enablejsapi=1"></iframe>
		</div>
		<!-- END OF SLIDES -->
		<div class="slide-arrow left"></div>
		<div class="slide-arrow right"></div>
	</div>
</body>