blog/urls.py
from blog.views import toggle_subscription
from django.urls import path, include
urlpatterns = [
    path(
        'api/',
        include([
            'toggle_subscription/<int:page_pk>/<category_pk>',
        ])
    )
]

blog_extension/urls.py
from django.urls.conf import path
from .views import submit_comment, toggle_subscription, contact_view
urlpatterns = [
    path('submit_form/', submit_comment, name='submit_comment'),
    path('toggle_subscription/',
         toggle_subscription, name='toggle_subscription'),
    path('contact_form/', contact_view, name='submit_contact_form')
]

app_name = 'blog_extension'

cmswagtail/urls.py
from blog.feeds import AtomFeed, RssFeed
from django.conf import settings
from django.conf.urls import url
from django.urls import include, path
from django.contrib import admin
from django.urls.conf import re_path
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls
from search import views as search_views
from django.views.generic import TemplateView
from wagtail.images.views.serve import ServeView
from wagtail.contrib.sitemaps.views import sitemap
urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('sitemap.xml', sitemap),
    path('robots.txt', include('robots.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),
    path('search/', search_views.search, name='search'),
    path('accounts/', include('allauth.urls')),
    path('accounts/login/success',
         TemplateView.as_view(template_name='account/redirect_login.html')),
    path('api/', include('blog_extension.urls')),
    path('rss/', RssFeed(), name='rssfeed'),
    path('atom/', AtomFeed(), name='atomfeed'),
]
if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
urlpatterns = urlpatterns + [
    re_path(r'^images/([^/]*)/(\d*)/([^/]*)/[^/]*$',
            ServeView.as_view(), name='wagtailimages_serve'),
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),
    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

blog/models.py
from blog_extension.forms import ContactForm
from django.db import models
from django.db.models.fields import URLField
from django.utils import timezone
from modelcluster.contrib.taggit import ClusterTaggableManager
from modelcluster.fields import ParentalKey
from taggit.models import TaggedItemBase
from wagtail.admin.edit_handlers import (FieldPanel, InlinePanel,
                                         StreamFieldPanel)
from wagtail.core import blocks
from wagtail.core.blocks.field_block import CharBlock, RichTextBlock, URLBlock
from wagtail.core.blocks.list_block import ListBlock
from wagtail.core.fields import RichTextField, StreamField
from wagtail.core.models import Page
from wagtail.embeds.blocks import EmbedBlock
from wagtail.images.blocks import ImageChooserBlock
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.search import index
from wagtail.snippets.edit_handlers import SnippetChooserPanel
from wagtail.snippets.models import register_snippet

# Particular Projects shown on the Website Homepage


class Project(models.Model):
    image = models.ForeignKey(
        'wagtailimages.Image', null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=40)
    description = RichTextField()
    carousel_images = StreamField([
        ('image', ImageChooserBlock()),
        ('video', EmbedBlock())
    ], null=True, blank=True)
    website_url = URLField(null=True)
    discord_url = URLField(null=True)
    youtube_url = URLField(null=True)

    def __str__(self):
        return self.title
    panels = [
        ImageChooserPanel('image'),
        FieldPanel('title'),
        FieldPanel('description'),
        StreamFieldPanel('carousel_images'),
        FieldPanel('website_url'),
        FieldPanel('discord_url'),
        FieldPanel('youtube_url')
    ]

# A Page for Blog Indexes or BROAD Categories in General


class BlogIndexPage(Page):
    'BLOG INDEX PAGE CONTAINING THE LIST OF ALL THE BLOG PAGES (ARTICLES) THAT ARE CHILDREN OF THIS PAGE'
    intro = RichTextField(blank=True)
    content_panels = Page.content_panels + [
        FieldPanel('intro', classname="full")
    ]

    def get_context(self, request):
        # Update context to include only published posts, ordered by reverse-chron
        context = super().get_context(request)
        context['all_categories'] = BlogCategory.objects.filter(
            blog_type=self)

        blogs = BlogPage.objects.live().descendant_of(
            self).order_by('-date')

        context['blogs_by_category'] = {
            category: blogs.filter(
                categories__blog_category=category) for category in context['all_categories']
        }

        # paginator = Paginator(blogs, 20)
        # # Try to get the ?page=x value
        # page = request.GET.get("page")
        # try:
        #     # If the page exists and the ?page=x is an int
        #     posts = paginator.page(page)
        # except PageNotAnInteger:
        #     # If the ?page=x is not an int; show the first page
        #     posts = paginator.page(1)
        # except EmptyPage:
        #     # If the ?page=x is out of range (too high most likely)
        #     # Then return the last page
        #     posts = paginator.page(paginator.num_pages)
        context['blogs'] = blogs
        return context


class BlogPageTag(TaggedItemBase):
    content_object = ParentalKey(
        'BlogPage',
        related_name='tagged_items',
        on_delete=models.CASCADE
    )


@register_snippet
class BlogCategory(models.Model):
    name = models.CharField(max_length=255)
    blog_type = ParentalKey(
        'blog.BlogIndexPage', on_delete=models.CASCADE, related_name='blog_type_categories')
    slug = models.SlugField(unique=True, max_length=80)
    panels = [
        FieldPanel('name'),
        FieldPanel('blog_type'),
        FieldPanel('slug'),
    ]

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"


class BlogPageBlogCategory(models.Model):
    page = ParentalKey(
        'blog.BlogPage', on_delete=models.CASCADE, related_name='categories')
    blog_category = models.ForeignKey(
        'blog.BlogCategory', on_delete=models.CASCADE, related_name='pages')

    panels = [
        SnippetChooserPanel('blog_category'),
    ]

    class Meta:
        unique_together = ('page', 'blog_category')

    def __str__(self):
        return self.blog_category.name


class BlogTagIndexPage(Page):
    def get_context(self, request):
        # Filter by tag
        tag = request.GET.get('tag')
        blogs = BlogPage.objects.filter(tags__name=tag)
        # Update template context
        context = super().get_context(request)
        context['tag'] = tag
        context['blog_pages'] = blogs
        return context


# Blog Page with the full content


class BlogPage(Page):
    'BLOG PAGE WHICH IS THE MAIN OF THE ARTICLE CONTAINING OF THE ARTICLE'
    date = models.DateField("Post date", default=timezone.now, editable=True)
    read_time = models.CharField(max_length=20)
    tags = ClusterTaggableManager(through=BlogPageTag, blank=True)
    body = RichTextField(features=[
        'h2', 'h3', 'bold', 'italic', 'link',
        'ol', 'ul', 'hr', 'document-link', 'image', 'embed', 'code', 'blockquote'
    ])
    player_embed = models.URLField(blank=True)
    search_fields = Page.search_fields + [
        index.SearchField('body'),
        index.RelatedFields('owner', [
            index.SearchField('last_name'),
            index.SearchField('first_name'),
        ]),

    ]
    content_panels = [
        FieldPanel('title'),
        FieldPanel('body'),
        InlinePanel('categories', label='category'),
        FieldPanel('tags'),
        FieldPanel('date'),
        FieldPanel('read_time'),
    ]

    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request, *args, **kwargs)
        context['all_categories'] = self.get_parent(
        ).specific.blog_type_categories.all()
        context['categories'] = BlogCategory.objects.filter(pages__page=self)
        # if request.user.is_anonymous:
        #     context['form1'] = BlogLoginForm()
        #     context['form2'] = BlogSignUpForm()
        # else:
        #     context['comment_form'] = CommentForm(
        #         initial={'blog_page_slug': self.slug})
        context['prev_blog'] = self.get_prev_siblings(
        ).live().type(BlogPage).first()
        context['next_blog'] = self.get_next_siblings(
        ).live().type(BlogPage).first()
        return context

# About Page

# Tab / Wagtail StructBlock for Legal Content like Terms, Privacy Policy


class LegalTab(blocks.StructBlock):
    name = CharBlock()
    body = RichTextBlock()

    class Meta:
        label = 'Legal Info Tab. Tab for legal Information such as Privacy Policy and Terms and Conditions'
        template = 'blog/blocks/legal_block.html'

# Tab / Wagtail StructBlock for Clients Carousel

    class Meta:
        label = 'Client Tab. Tab to show the clients'


# Tab / Wagtail StructBlock for Contact Us form
class ContactTab(blocks.StructBlock):
    name = CharBlock()
    subject_prefix = CharBlock()

    class Meta:
        template = 'blog/blocks/contact_block.html'
        label = 'Contact Us Tab. A Tab for Contact including the name of the tab'
        'And the subject prefixed before the contact\'s subject'


# Tab / Wagtail StructBlock for Team Carousel
class TeamTab(blocks.StructBlock):
    name = CharBlock()
    children = blocks.ListBlock(
        blocks.StructBlock([
            ('name', CharBlock()),
            ('role', CharBlock()),
            ('project_description', CharBlock()),
            ('personal_description', CharBlock()),
            ('image', ImageChooserBlock()),
            ('twitter', URLBlock(required=False)),
            ('linkedin', URLBlock(required=False)),
            ('instagram', URLBlock(required=False)),
            ('github', URLBlock(required=False)),
            ('youtube', URLBlock(required=False))
        ]),

    )

    class Meta:
        template = 'blog/blocks/team_block.html'
        label = 'Team Tab. A tab to show the team members and contributors '


# Tab / Wagtail for Appointment related Third Party Iframe [pure static html]
class AppointmentTab(blocks.StructBlock):
    name = CharBlock()

    class Meta:
        template = 'blog/blocks/appointment_block.html'
        label = 'Appointment Tab. A tab for iframe such as calendly for Appointments, The Iframe can only be changed in code for security reasons.'

# About Page containing all the above coded Tabs


class AboutPage(Page):
    description = RichTextField(null=True)
    body = RichTextField(features=[
        'h2', 'h3', 'bold', 'italic', 'link',
        'ol', 'ul', 'hr', 'document-link', 'image', 'embed', 'code', 'blockquote'
    ])
    tabs = StreamField([
        ('legal', LegalTab()),
        ('team', TeamTab()),
        ('contact_us', ContactTab()),
        ('appointment', AppointmentTab())
    ])
    content_panels = Page.content_panels + [
        FieldPanel('description'),
        FieldPanel('body'),
        StreamFieldPanel('tabs')
    ]

    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request, *args, **kwargs)
        context['contact_form'] = ContactForm()
        return context


class LegalPage(Page):
    description = RichTextField()
    tabs = StreamField([
        ('legal', LegalTab()),
    ])
    content_panels = Page.content_panels + [
        FieldPanel('description'),
        StreamFieldPanel('tabs')
    ]


class FooterLink(models.Model):
    link_name = models.CharField(default="", max_length=40)
    link = URLField()

    def __str__(self):
        return self.link_name

blog_extension/models.py
from django.db import models
from wagtail.snippets.models import register_snippet
from django.contrib.auth import get_user_model
# Create your models here.

User = get_user_model()


@register_snippet
class Like(models.Model):
    blog_page = models.ForeignKey('blog.BlogPage', on_delete=models.CASCADE)
    liked_by = models.ForeignKey(
        'user_management.User', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'like'
        verbose_name_plural = 'likes'


@register_snippet
class Comment(models.Model):
    comment_text = models.TextField()
    blog_page = models.ForeignKey('blog.BlogPage', on_delete=models.CASCADE)
    comment_by = models.ForeignKey(
        'user_management.User', on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    parent = models.ForeignKey(
        'self', blank=True, null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'comment'
        verbose_name_plural = 'comments'
        ordering = ['created_on']


class Subscriptions(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    category_subscription = models.ManyToManyField(
        'blog.BlogCategory', related_name='subscribers', blank=True
    )

    def __str__(self):
        return self.user.email

cmswagtail/templates/blog/about_page.html
{% extends "base.html" %}
{% load static %}
{% load wagtailcore_tags wagtailimages_tags %}
{% block body_class %}template-blogpage{% endblock %}
{% block content %}
<br>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="title txt-sm-center txt-xs-center mt-0">
        <h4 id="about-title">{{ page.title }}<span class="red-dot"></span></h4>
        <div id="about_section">
          <div style="display: flex; justify-content:center">
          <img id="about-description" src="{% static 'images/harsh.jpeg'%}">
          </div>
          <br>
          <br>
        </div>
        <div>
          <div id="content-hideable">
            <div class="views-element-container widget">
              <button class="btn btn-color-out " data-toggle="modal" data-target="#subscribeModal">
                Manage Subscriptions
              </button>
            </div>
            {% include 'components/support.html' %}
          </div>
          {% include 'components/follow_me.html' %}
        </div>
      </div>
    </div>
    <div class="col-md-7">
      
      <ul role="tablist" class="nav nav-tabs outline">
        <li role="presentation" class="active"><a href="#aboutus" role="tab" data-toggle="tab">About</a>
        </li>
        {% for tab in page.tabs %}
        <li role="presentation">
          <a href="#{{ tab.value.name|slugify }}" role="tab" data-toggle="tab">
            {{ tab.value.name }}
          </a>
        </li>
        {% endfor %}
      </ul>
      <div class="tab-content">
        <div id="aboutus" role="tabpanel" class="tab-pane fade in active text-justify">
        
          {{ page.body|richtext }}
        </div>
        {% for tab in page.tabs %}
        <div id="{{ tab.value.name|slugify }}" role="tabpanel" class="tab-pane fade in text-justify">
            
            {% if tab.block_type == 'appointment' %}
              {% include_block tab with form=contact_form %}
            {% else %}
              {% include_block tab %}
            {% endif %}
        </div>
        {% endfor %}
      </div>
    </div>
    </div>
    </div>
{% endblock %}

{% block scripts %}
  
<script>
  $("#contact-us-form").submit(
      function(e){
          e.preventDefault();
          const $button = $('#contact-form-submit')
          $button.removeClass('btn-danger');
          $button.addClass('btn-primary');
          $button.text('Submitting Contact form');
          $.ajax({
              data: $(this).serialize(),
              type: 'POST',
              url: "{% url 'blog_extension:submit_contact_form' %}",
              success: function () {
                  $button.removeClass('btn-primary');
                  swal('Success', 'Your Query has been sent', 'success')
                  $button.text('Submit Your Query.');
              },
              error: function () {
                  $button.addClass('btn-danger');
                  $button.text('Error','Your Query could not be sent', 'error');
              }
          });
      }
  )
</script>
<script>
  const elementId = window.location.hash.substr(1);
  const element = document.getElementById(elementId);
  if( element && element.classList.contains('tab-pane')){
    element.classList.add('active', 'in');
    document.getElementById('aboutus').classList.remove('active', 'in');
    document.querySelector(`a[href=\"#${elementId}\"]`).parentElement.classList.add('active');
    document.querySelector('a[href="#aboutus"').parentElement.classList.remove('active');
  };
</script>
<script src="{% static 'getharshJS/aboutPageJs.js' %}"></script>
{% endblock scripts %}
  

cmswagtail/templates/blog/blog_index_page.html
{% extends "base.html" %}
{% load custom_tags %}
{% load static wagtailembeds_tags %}
{% load wagtailcore_tags wagtailimages_tags %}
{% block body_class %}template-blogindexpage{% endblock %}
{% block content %}
<br>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="title txt-sm-center txt-xs-center mt-0">
        <h4>{{ page.title }}<span class="red-dot"></span></h4>
        <div class="serif" style="text-align: justify;">{{page.intro|richtext }}</div>
        <div class="fixed-scroll">
            
          <div class="views-element-container widget">
            <button class="btn btn-color-out" data-toggle="modal" data-target="#subscribeModal">
              Manage Subscriptions
            </button>
          </div>
          {% include 'components/support.html' %}
          {% include 'components/follow_me.html' %}
        </div>
      </div>
    </div>
    <div class="col-md-7 col-md-offset-1">
      <ul role="tablist" class="nav nav-tabs outline">
        <li role="presentation" class="active"><a href="#latest" style="font-weight: 600;" role="tab" data-toggle="tab">Latest</a>
        </li>
        {% for category in all_categories %}
        <li role="presentation"><a href="#{{ category|lower }}" role="tab" style="font-weight: 600;" data-toggle="tab">{{ category }}</a>
        </li>
        {% endfor %}
      </ul>
      <div class="tab-content" onload="category_select();">
        <div id="latest" role="tabpanel" class="tab-pane fade in active">
          <div class="masonry-post">
            {% for post in blogs %}
            {% with post=post.specific %}
            <div class="blog-post">
              <div class="post-body">
                <h3 class="serif"><a href="{% pageurl post %}">{{ post.title }}</a></h3>
                <p class="serif">{{ post.body|richtext|truncatewords_html:20 }}</p>
                <div class="post-info upper"><span
                    class="pull-right black-text">{{ post.read_time }} read | By {{ post.owner.get_full_name }} | {{ post.date }}</span>
                </div>
              </div>
            </div>
            {% endwith %}
            {% endfor %}
          </div>
        </div>

        {% for category in all_categories %}
        <div id="{{ category|lower }}" role="tabpanel" class="tab-pane fade in">
          <!-- insert boxes -->
          <div class="masonry-post">
            {% for post in blogs_by_category|get_item:category %}
            {% with post=post.specific %}
            <div class="blog-post">
              <div class="post-body">
                <h3 class="serif"><a href="{% pageurl post %}">{{ post.title }}</a></h3>
                <p class="serif">{{ post.body|richtext|truncatewords_html:20 }}</p>
                <div class="post-info upper"><span
                    class="pull-right black-text">{{ post.read_time }} read | By {{ post.owner.get_full_name }} | {{ post.date }}</span>
                </div>
              </div>
            </div>
            {% endwith %}
            {% empty %}
            <h3>No articles in this category</h3>
            {% endfor %}
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{% endblock %}


{% block scripts %}
<script>
  const form_auth_control = document.querySelector('#form-auth-control');
  console.log(form_auth_control);
  if (form_auth_control)
    form_auth_control.addEventListener('click', function (e) {
      const form_auth = $('#form-auth');
      console.log(form_auth);
      $(form_auth).fadeIn();
      $(form_auth_control).fadeOut();
      localStorage.setItem('path', window.location.toString());
    });
</script>
<script>
  const elementId = window.location.hash.substr(1);
  const element = document.getElementById(elementId);
  if( element && element.classList.contains('tab-pane')){
    element.classList.add('active', 'in');
    document.getElementById('latest').classList.remove('active', 'in');
    document.querySelector(`a[href=\"#${elementId}\"]`).parentElement.classList.add('active');
    document.querySelector('a[href="#latest"').parentElement.classList.remove('active');
  };
</script>
{% endblock scripts %}

cmswagtail/templates/blog/blog_page.html
{% extends "base.html" %}
{% load static %}
{% load wagtailcore_tags wagtailimages_tags wagtailembeds_tags%}
{% load social_share %}
{% load socialaccount %}
{% block body_class %}template-blogpage{% endblock %}
{% block content %}
<br>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="title txt-sm-center txt-xs-center mt-0">
        <h4 class="default">{{ page.title }}</h4>
        <p class="serif">{{page.intro|richtext }}</p>
        <h6 class="upper">
          <span>
            {% if page.owner.wagtail_userprofile.avatar %} 
            <img width="35px" height="35px" src="{{ page.owner.wagtail_userprofile.avatar.url }}" alt=""
              style="border-radius: 50%;">
             {% endif %} 
            <span>{{ page.owner.get_full_name }}</span>
          </span>
          <span class="dot"></span><span>{{ page.date }}</span><span class="dot"></span>
        </h6>
      </div>
      <div class="views-element-container widget">
        <div class="tags clearfix">

          {% if next_blog %}
          <a href="{% pageurl next_blog %}">Next Blog</a>
          {% endif %}
          {% if prev_blog %}
          <a href="{% pageurl prev_blog %}">Previous Blog</a>
          {% endif %}

        </div>
      </div>
      <div class="fixed-scroll">
        
        {% if page.player_embed %}
        <div class="media-audio">
          {% embed page.player_embed %}
        </div>
        {% endif %}
          
        {% include 'components/share.html' %}      
        <div class="views-element-container widget">
          <h6 class="upper">Subscribe</h6>
          <button class="btn btn-color-out" data-toggle="modal" data-target="#subscribeModal">
            Manage Subscriptions
          </button>
        </div>
  
        {% if page.tags.all.count %}
        <div class="views-element-container widget">
          <h6 class="upper">Associated Tags</h6>
          <div class="tags clearfix">
            {% for tag in page.tags.all %}
            <a href="{% slugurl 'tags' %}?tag={{ tag }}">{{ tag }}</a>
            {% endfor %}
          </div>
        </div>
        {% endif %}
  
  
      </div>

    </div>
    <div class="col-md-7 col-md-offset-1">
      <ul role="tablist" class="nav nav-tabs outline">
        <li role="presentation" class="active"><a href="#latest" style="font-weight: 600;" role="tab"
            data-toggle="tab">Blog</a>
        </li>
        {% for category in all_categories %}
        <li role="presentation"><a class="atab" href="{{ page.get_parent.url }}#{{ category|lower }}"
            style="font-weight: 600;" role="tab" data-toggle="tab">

            {% if category in categories %}
            <strong style="color: #42b8d4;">
              {{ category }}
            </strong>
            {% else %}
            {{ category }}
            {% endif %}

          </a>
        </li>
        {% endfor %}
      </ul>
      <div class="tab-content">
        <div id="latest" role="tabpanel" class="tab-pane fade in active">
          <div class="text-justify">
              {{ page.body|richtext }}

          </div>
          </article>
          <br>
          <hr>

          {% comment %}
          <div id="comments">
            <br>
            {% if user.is_authenticated %}
            <h5 id="reply-title">LEAVE A COMMENT <small><a rel="nofollow" id="cancel-comment-reply-link" href="#"
                  style="display:none;">Cancel reply</a></small></h5>
            <!-- .commentform -->
            <form action="{% url 'blog_extension:submit_comment' %}" method="post" id="commentform"
              class="validate-form" novalidate="novalidate">
              {% csrf_token %}
              <p class="comment-notes">Your email address will not be published. Required fields are marked
                <span class="required" aria-required="true">*</span>
              </p>
              {{ comment_form.as_p }}
              <p class="form-submit">
                <input type="submit" name="submit" id="submit" class="btn btn-color-out" value="Post Comment">
              </p>
            </form>
            <!-- .commentform -->
            {% else %}
            <h3>Login or Signup to Continue</h3>
            <h3>
              <div class="views-element-container widget">
                <div class="tags clearfix">
                  <a href="#"
                    onclick="window.open('{% provider_login_url 'google' %}', '_blank', 'location=yes,height=570,width=520,scrollbars=yes,status=yes');"
                    hreflang="en">
                    <i class="fa fa-google-plus fa-2x "></i></i></a>
                  <a href="#"
                    onclick="window.open('{% provider_login_url 'github' %}', '_blank', 'location=yes,height=570,width=520,scrollbars=yes,status=yes');"
                    hreflang="en">
                    <i class="fa fa-github fa-2x "></i></a>
                  <a href="#"
                    onclick="window.open('{% provider_login_url 'facebook' %}', '_blank', 'location=yes,height=570,width=520,scrollbars=yes,status=yes');"
                    hreflang="en">
                    <i class="fa fa-facebook fa-2x "></i></a>
                  <a href="#"
                    onclick="window.open('{% provider_login_url 'twitter' %}', '_blank', 'location=yes,height=570,width=520,scrollbars=yes,status=yes');"
                    hreflang="en">
                    <i class="fa fa-twitter fa-2x "></i></a>
                </div>
              </div>
            </h3>
            {% endif %}
            <ul class="comments-list">
              <a id="comment-8"></a>
              {% for comment in page.comment_set.all %}
              <li>
                <div class="comment">
                  <div class="comment-pic">
                    {% if comment.comment_by.socialaccount_set.all.0.get_avatar_url %}
                    <img width="35px" height="35px"
                      src="{{ comment.comment_by.socialaccount_set.all.0.get_avatar_url }}" alt="">

                    {% else %}
                    <img src="{% static 'images/user-01.png' %}" width="35px" height="35px" alt="no-avatar" />
                    {% endif %}
                  </div>
                  <div class="comment-text">
                    <h5 class="upper">
                      <span style="margin-right: 100%;">
                        <span>
                          {{ comment.comment_by.username }}
                        </span>
                      </span>
                      <span style="float: inline-end; font-size: 12px;">{{ comment.created_on }}</span>

                    </h5>
                    <p>
                      {{ comment.comment_text }}
                    </p>
                    <ul class="links inline">
                      <li class="comment-forbidden"></li>
                    </ul>
                  </div>
                </div>
              </li>
              {% endfor %}
            </ul>
          </div>
          {% endcomment %}
        </div>
      </div>
    </div>
  </div>
</div>
</section>
{% endblock %}
{% block scripts %}

<!-- <script>
  const form_auth_control = document.querySelector('#form-auth-control');
  console.log(form_auth_control);
  if(form_auth_control)
    form_auth_control.addEventListener('click', function (e) {
      const form_auth = $('#form-auth');
      console.log(form_auth);
      $(form_auth).fadeIn();
      $(form_auth_control).fadeOut();
      localStorage.setItem('path', window.location.toString());
    });
</script> -->
<script>
  const copy_link_button = document.getElementById('copy-link');
  copy_link_button.addEventListener('click', function (e) {
    e.preventDefault();
    navigator.clipboard.writeText(window.location.toString())
      .then(
        function () {
          copy_link_button.innerHTML = '<i class="fa fa-check fa-2x" aria-hidden="true"></i>';
          setTimeout(function () {
            copy_link_button.innerHTML = '<i class="fa fa-copy fa-2x" aria-hidden="true"></i>';
          }, 3000
          );
        },
        function (err) {
          console.error('Could not copy text: ', err);
        }
      )
  })
</script>
<script>
  $("textarea").css('overflow', 'hidden');
  $("textarea").keyup(function (e) {
    while ($(this).outerHeight() < this.scrollHeight + parseFloat($(this).css("borderTopWidth")) + parseFloat($(this).css("borderBottomWidth"))) {
      $(this).height($(this).height() + 1);
    };
  });
</script>
<script>
  $(document).ready(function () {
    $('.atab').click(
      function (e) {
        window.location = $(this).attr('href');
      }
    )
  });

</script>
<script>
  const embeds = document.querySelectorAll('div>iframe');
  embeds.forEach(embed => {
    if (embed.src.includes('soundcloud')) {
      embed.parentElement.classList.add('media-audio');
    }
    else {
      embed.parentElement.classList.add('media-video');
    }
  });

</script>
{% endblock scripts %}